# Generated by Django 3.1 on 2022-12-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0003_auto_20221209_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='conversation',
            new_name='ticket_conversation',
        ),
    ]
