# Generated by Django 3.1 on 2022-12-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0005_auto_20221210_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
