# Generated by Django 3.1 on 2022-12-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createquote', '0003_auto_20221210_1323'),
        ('ticketApp', '0006_delete_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createquote.project'),
        ),
    ]
