# Generated by Django 3.1 on 2022-12-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='A Simple Company', max_length=24)),
                ('email', models.EmailField(max_length=25)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('company_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('website', models.URLField(max_length=100)),
                ('budget', models.CharField(max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='createquote.company')),
            ],
        ),
    ]
