# Generated by Django 3.1 on 2022-12-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createquote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='A Simple Company', max_length=24),
        ),
    ]
