# Generated by Django 3.1 on 2022-12-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createquote', '0002_company_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='createquote.company'),
        ),
    ]
