# Generated by Django 3.1 on 2022-11-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createquote', '0002_alter_client_id_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
