# Generated by Django 3.1 on 2022-12-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createquote', '0003_auto_20221210_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user_company',
            new_name='company_owner',
        ),
    ]
