# Generated by Django 4.2.17 on 2025-01-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createquote', '0004_auto_20221212_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
